project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!eng/**"

website:
  title: "Initiation au Distant Viewing"
  sidebar:
    style: docked
    search: true
    contents:
      - file: notebook01.qmd
        text: Tutoriel I
      - file: notebook02.qmd
        text: Tutoriel II
      - file: notebook03.qmd
        text: Tutoriel III

format:
  html:
    code-fold: true
    code-summary: "View code"
    code-tools: true
    include-after-body: fix-code-toggle.html
    theme:
      - cosmo
      - custom.scss
    lightbox: true

execute:
  echo: true
  eval: true
